(defun flip ()
  (princ "heads or tails: ")
  (setf a (string-downcase (read)))
  (if (or (string= a "heads") (string= a "tails"))
    (princ a)
    (flip)))

(flip)
(terpri)
(setf y (list 2 1 ))
(setf z (nth (random (length y) (make-random-state t)) y))
(if (= z 1)
  (princ "You win"))
(if (= z 2)
  (princ "You loose"))